# dfc-shared pipeline
# contains release stages that have a condition set to false (so they never run)
# these can be enabled again when YAML releases are production ready 

variables:
- name: SolutionBaseName
  value: Dfc.Shared

resources:
  repositories:
  - repository: self
  - repository: 'dfc-devops'
    type: github
    name: olusola-adio/dfc-devops
    endpoint: 'olusola-adio'
    ref: refs/tags/v1.11.1

pr:
  branches:
    include:
    - master

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: TestAndPublish
    variables:
      - group: 'KeyVault - dfc-dev-shared-kv'
      - group: dfc-shared-infrastructure-dev
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources'
        SolutionBaseName: $(SolutionBaseName)
        TokenizeTestParameters: true
    - task: CopyFiles@2
      displayName: 'Copy PSScripts Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'PSScripts/**/*.ps1'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Resources/PSScripts'
        flattenFolders: true
    - task: PublishBuildArtifacts@2
      displayName: Publish PSScripts Pipeline Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/Resources/PSScripts
        artifactName: Dfc.Shared.Resources.PSScripts
    - task: PublishBuildArtifacts@2
      displayName: Publish AksManifests Pipeline Artifact
      inputs:
        targetPath: Resources/AksManifests
        artifactName: Dfc.Shared.Resources.AksManifests
    - task: ArchiveFiles@2
      displayName: 'Archive FunctionApp'
      inputs:
        rootFolderOrFile: FunctionApp
        includeRootFolder: false
        archiveFile: '$(System.DefaultWorkingDirectory)/zip/FunctionApp.zip'
    - task: PublishBuildArtifacts@2
      displayName: Publish FunctionApp Pipeline Artifact
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'
